FROM node:18

# Create app directory

WORKDIR /usr/appstellar-stellar-web

COPY package*.json /usr/appsteallar-stellar-web/

RUN npm install

COPY . /usr/appsteallar-stellar-web/

RUN npm run build

COPY . /usr/appstellar-steallar-web/

EXPOSE 3000

CMD [ "npm" , "run", "start"]
