apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.ingressName}}
  namespace: {{.Values.namepace}}
spec:
  ingressClassName:
  rules:
  - host: ardin.appstellar.training
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-service
            port:
              number: 80 