apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000