name: deploy-prod

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  AWS_ECR_URI: ""

permissions:
  id-token: write
  contents: read

jobs:
  DeployProd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup AWS/CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Build and push image
        run: |

          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 313422618945.dkr.ecr.eu-central-1.amazonaws.com
          cd ./appsteallar-ick-training-web
          docker build -f ./Dockerfile -t webapp .
          docker tag webapp  ${{ env.AWS_ECR_URI }}:dev
          docker push ${{ env.AWS_ECR_URI }}:dev

          