name: deploy-prod

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  AWS_ECR_URI: ""

permissions:
  id-token: write
  contents: read

jobs:
  DeployProd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          docker build -f ./Dockerfile -t webapp .
          docker tag webapp  ${{ env.AWS_ECR_URI }}:dev
          docker push ${{ env.AWS_ECR_URI }}:dev